const countriesList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas The",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Cook Islands",
  "Costa Rica",
  "Cote D'Ivoire (Ivory Coast)",
  "Croatia (Hrvatska)",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic Of The Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji Islands",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia The",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey and Alderney",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and McDonald Islands",
  "Honduras",
  "Hong Kong S.A.R.",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea North",
  "Korea South",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau S.A.R.",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Man (Isle of)",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands Antilles",
  "Netherlands The",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory Occupied",
  "Panama",
  "Papua new Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn Island",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic Of The Congo",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Helena",
  "Saint Kitts And Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent And The Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Smaller Territories of the UK",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard And Jan Mayen Islands",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad And Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks And Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City State (Holy See)",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (British)",
  "Virgin Islands (US)",
  "Wallis And Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Yugoslavia",
  "Zambia",
  "Zimbabwe"
]

//Tamilnadu is example state
const statesForACountryList = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kenmore",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Narora",
  "Odisha",
  "Pondicherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
]

const citiesInAState = [
  "Abiramam",
  "Achampudur",
  "Acharapakkam",
  "Acharipallam",
  "Achipatti",
  "Adikaratti",
  "Adiramapattinam",
  "Aduturai",
  "Adyar",
  "Agaram",
  "Agasthiswaram",
  "Akkaraipettai",
  "Alagappapuram",
  "Alagapuri",
  "Alampalayam",
  "Alandur",
  "Alanganallur",
  "Alangayam",
  "Alangudi",
  "Alangulam",
  "Alanthurai",
  "Alapakkam",
  "Allapuram",
  "Alur",
  "Alwar Tirunagari",
  "Alwarkurichi",
  "Ambasamudram",
  "Ambur",
  "Ammainaickanur",
  "Ammaparikuppam",
  "Ammapettai",
  "Ammavarikuppam",
  "Ammur",
  "Anaimalai",
  "Anaiyur",
  "Anakaputhur",
  "Ananthapuram",
  "Andanappettai",
  "Andipalayam",
  "Andippatti",
  "Anjugramam",
  "Annamalainagar",
  "Annavasal",
  "Annur",
  "Anthiyur",
  "Appakudal",
  "Arachalur",
  "Arakandanallur",
  "Arakonam",
  "Aralvaimozhi",
  "Arani",
  "Arani Road",
  "Arantangi",
  "Arasiramani",
  "Aravakurichi",
  "Aravankadu",
  "Arcot",
  "Arimalam",
  "Ariyalur",
  "Ariyappampalayam",
  "Ariyur",
  "Arni",
  "Arulmigu Thirumuruganpundi",
  "Arumanai",
  "Arumbavur",
  "Arumuganeri",
  "Aruppukkottai",
  "Ashokapuram",
  "Athani",
  "Athanur",
  "Athimarapatti",
  "Athipattu",
  "Athur",
  "Attayyampatti",
  "Attur",
  "Auroville",
  "Avadattur",
  "Avadi",
  "Avalpundurai",
  "Avaniapuram",
  "Avinashi",
  "Ayakudi",
  "Ayanadaippu",
  "Aygudi",
  "Ayothiapattinam",
  "Ayyalur",
  "Ayyampalayam",
  "Ayyampettai",
  "Azhagiapandiapuram",
  "Balakrishnampatti",
  "Balakrishnapuram",
  "Balapallam",
  "Balasamudram",
  "Bargur",
  "Belur",
  "Berhatty",
  "Bhavani",
  "Bhawanisagar",
  "Bhuvanagiri",
  "Bikketti",
  "Bodinayakkanur",
  "Brahmana Periya Agraharam",
  "Buthapandi",
  "Buthipuram",
  "Chatrapatti",
  "Chembarambakkam",
  "Chengalpattu",
  "Chengam",
  "Chennai",
  "Chennasamudram",
  "Chennimalai",
  "Cheranmadevi",
  "Cheruvanki",
  "Chetpet",
  "Chettiarpatti",
  "Chettipalaiyam",
  "Chettipalayam Cantonment",
  "Chettithangal",
  "Cheyur",
  "Cheyyar",
  "Chidambaram",
  "Chinalapatti",
  "Chinna Anuppanadi",
  "Chinna Salem",
  "Chinnakkampalayam",
  "Chinnammanur",
  "Chinnampalaiyam",
  "Chinnasekkadu",
  "Chinnavedampatti",
  "Chitlapakkam",
  "Chittodu",
  "Cholapuram",
  "Coimbatore",
  "Coonoor",
  "Courtalam",
  "Cuddalore",
  "Dalavaipatti",
  "Darasuram",
  "Denkanikottai",
  "Desur",
  "Devadanapatti",
  "Devakkottai",
  "Devakottai",
  "Devanangurichi",
  "Devarshola",
  "Devasthanam",
  "Dhalavoipuram",
  "Dhali",
  "Dhaliyur",
  "Dharapadavedu",
  "Dharapuram",
  "Dharmapuri",
  "Dindigul",
  "Dusi",
  "Edaganasalai",
  "Edaikodu",
  "Edakalinadu",
  "Elathur",
  "Elayirampannai",
  "Elumalai",
  "Eral",
  "Eraniel",
  "Eriodu",
  "Erode",
  "Erumaipatti",
  "Eruvadi",
  "Ethapur",
  "Ettaiyapuram",
  "Ettimadai",
  "Ezhudesam",
  "Ganapathipuram",
  "Gandhi Nagar",
  "Gangaikondan",
  "Gangavalli",
  "Ganguvarpatti",
  "Gingi",
  "Gopalasamudram",
  "Gopichettipalaiyam",
  "Gudalur",
  "Gudiyattam",
  "Guduvanchery",
  "Gummidipoondi",
  "Hanumanthampatti",
  "Harur",
  "Harveypatti",
  "Highways",
  "Hosur",
  "Hubbathala",
  "Huligal",
  "Idappadi",
  "Idikarai",
  "Ilampillai",
  "Ilanji",
  "Iluppaiyurani",
  "Iluppur",
  "Inam Karur",
  "Injambakkam",
  "Irugur",
  "Jaffrabad",
  "Jagathala",
  "Jalakandapuram",
  "Jalladiampet",
  "Jambai",
  "Jayankondam",
  "Jolarpet",
  "Kadambur",
  "Kadathur",
  "Kadayal",
  "Kadayampatti",
  "Kadayanallur",
  "Kadiapatti",
  "Kalakkad",
  "Kalambur",
  "Kalapatti",
  "Kalappanaickenpatti",
  "Kalavai",
  "Kalinjur",
  "Kaliyakkavilai",
  "Kallakkurichi",
  "Kallakudi",
  "Kallidaikurichchi",
  "Kallukuttam",
  "Kallupatti",
  "Kalpakkam",
  "Kalugumalai",
  "Kamayagoundanpatti",
  "Kambainallur",
  "Kambam",
  "Kamuthi",
  "Kanadukathan",
  "Kanakkampalayam",
  "Kanam",
  "Kanchipuram",
  "Kandanur",
  "Kangayam",
  "Kangayampalayam",
  "Kangeyanallur",
  "Kaniyur",
  "Kanjikoil",
  "Kannadendal",
  "Kannamangalam",
  "Kannampalayam",
  "Kannankurichi",
  "Kannapalaiyam",
  "Kannivadi",
  "Kanyakumari",
  "Kappiyarai",
  "Karaikkudi",
  "Karamadai",
  "Karambakkam",
  "Karambakkudi",
  "Kariamangalam",
  "Kariapatti",
  "Karugampattur",
  "Karumandi Chellipalayam",
  "Karumathampatti",
  "Karumbakkam",
  "Karungal",
  "Karunguzhi",
  "Karuppur",
  "Karur",
  "Kasipalaiyam",
  "Kasipalayam G",
  "Kathirvedu",
  "Kathujuganapalli",
  "Katpadi",
  "Kattivakkam",
  "Kattumannarkoil",
  "Kattupakkam",
  "Kattuputhur",
  "Kaveripakkam",
  "Kaveripattinam",
  "Kavundampalaiyam",
  "Kavundampalayam",
  "Kayalpattinam",
  "Kayattar",
  "Kelamangalam",
  "Kelambakkam",
  "Kembainaickenpalayam",
  "Kethi",
  "Kilakarai",
  "Kilampadi",
  "Kilkulam",
  "Kilkunda",
  "Killiyur",
  "Killlai",
  "Kilpennathur",
  "Kilvelur",
  "Kinathukadavu",
  "Kiramangalam",
  "Kiranur",
  "Kiripatti",
  "Kizhapavur",
  "Kmarasamipatti",
  "Kochadai",
  "Kodaikanal",
  "Kodambakkam",
  "Kodavasal",
  "Kodumudi",
  "Kolachal",
  "Kolappalur",
  "Kolathupalayam",
  "Kolathur",
  "Kollankodu",
  "Kollankoil",
  "Komaralingam",
  "Komarapalayam",
  "Kombai",
  "Konakkarai",
  "Konavattam",
  "Kondalampatti",
  "Konganapuram",
  "Koradacheri",
  "Korampallam",
  "Kotagiri",
  "Kothinallur",
  "Kottaiyur",
  "Kottakuppam",
  "Kottaram",
  "Kottivakkam",
  "Kottur",
  "Kovilpatti",
  "Koyampattur",
  "Krishnagiri",
  "Krishnarayapuram",
  "Krishnasamudram",
  "Kuchanur",
  "Kuhalur",
  "Kulasekarappattinam",
  "Kulasekarapuram",
  "Kulithalai",
  "Kumarapalaiyam",
  "Kumarapalayam",
  "Kumarapuram",
  "Kumbakonam",
  "Kundrathur",
  "Kuniyamuthur",
  "Kunnathur",
  "Kunur",
  "Kuraikundu",
  "Kurichi",
  "Kurinjippadi",
  "Kurudampalaiyam",
  "Kurumbalur",
  "Kuthalam",
  "Kuthappar",
  "Kuttalam",
  "Kuttanallur",
  "Kuzhithurai",
  "Labbaikudikadu",
  "Lakkampatti",
  "Lalgudi",
  "Lalpet",
  "Llayangudi",
  "Madambakkam",
  "Madanur",
  "Madathukulam",
  "Madhavaram",
  "Madippakkam",
  "Madukkarai",
  "Madukkur",
  "Madurai",
  "Maduranthakam",
  "Maduravoyal",
  "Mahabalipuram",
  "Makkinanpatti",
  "Mallamuppampatti",
  "Mallankinaru",
  "Mallapuram",
  "Mallasamudram",
  "Mallur",
  "Mamallapuram",
  "Mamsapuram",
  "Manachanallur",
  "Manali",
  "Manalmedu",
  "Manalurpet",
  "Manamadurai",
  "Manapakkam",
  "Manapparai",
  "Manavalakurichi",
  "Mandaikadu",
  "Mandapam",
  "Mangadu",
  "Mangalam",
  "Mangalampet",
  "Manimutharu",
  "Mannargudi",
  "Mappilaiurani",
  "Maraimalai Nagar",
  "Marakkanam",
  "Maramangalathupatti",
  "Marandahalli",
  "Markayankottai",
  "Marudur",
  "Marungur",
  "Masinigudi",
  "Mathigiri",
  "Mattur",
  "Mayiladuthurai",
  "Mecheri",
  "Melacheval",
  "Melachokkanathapuram",
  "Melagaram",
  "Melamadai",
  "Melamaiyur",
  "Melanattam",
  "Melathiruppanthuruthi",
  "Melattur",
  "Melmananbedu",
  "Melpattampakkam",
  "Melur",
  "Melvisharam",
  "Mettupalayam",
  "Mettur",
  "Meyyanur",
  "Milavittan",
  "Minakshipuram",
  "Minambakkam",
  "Minjur",
  "Modakurichi",
  "Mohanur",
  "Mopperipalayam",
  "Mudalur",
  "Mudichur",
  "Mudukulathur",
  "Mukasipidariyur",
  "Mukkudal",
  "Mulagumudu",
  "Mulakaraipatti",
  "Mulanur",
  "Mullakkadu",
  "Muruganpalayam",
  "Musiri",
  "Muthupet",
  "Muthur",
  "Muttayyapuram",
  "Muttupet",
  "Muvarasampettai",
  "Myladi",
  "Mylapore",
  "Nadukkuthagai",
  "Naduvattam",
  "Nagapattinam",
  "Nagavakulam",
  "Nagercoil",
  "Nagojanahalli",
  "Nallampatti",
  "Nallur",
  "Namagiripettai",
  "Namakkal",
  "Nambiyur",
  "Nambutalai",
  "Nandambakkam",
  "Nandivaram",
  "Nangavalli",
  "Nangavaram",
  "Nanguneri",
  "Nanjikottai",
  "Nannilam",
  "Naranammalpuram",
  "Naranapuram",
  "Narasimhanaickenpalayam",
  "Narasingapuram",
  "Narasojipatti",
  "Naravarikuppam",
  "Nasiyanur",
  "Natham",
  "Nathampannai",
  "Natrampalli",
  "Nattam",
  "Nattapettai",
  "Nattarasankottai",
  "Navalpattu",
  "Nazarethpettai",
  "Nazerath",
  "Neikkarapatti",
  "Neiyyur",
  "Nellikkuppam",
  "Nelliyalam",
  "Nemili",
  "Nemilicheri",
  "Neripperichal",
  "Nerkunram",
  "Nerkuppai",
  "Nerunjipettai",
  "Neykkarappatti",
  "Neyveli",
  "Nidamangalam",
  "Nilagiri",
  "Nilakkottai",
  "Nilankarai",
  "Odaipatti",
  "Odaiyakulam",
  "Oddanchatram",
  "Odugathur",
  "Oggiyamduraipakkam",
  "Olagadam",
  "Omalur",
  "Ooty",
  "Orathanadu",
  "Othakadai",
  "Othakalmandapam",
  "Ottapparai",
  "Pacode",
  "Padaividu",
  "Padianallur",
  "Padirikuppam",
  "Padmanabhapuram",
  "Padririvedu",
  "Palaganangudy",
  "Palaimpatti",
  "Palakkodu",
  "Palamedu",
  "Palani",
  "Palani Chettipatti",
  "Palavakkam",
  "Palavansathu",
  "Palayakayal",
  "Palayam",
  "Palayamkottai",
  "Palladam",
  "Pallapalayam",
  "Pallapatti",
  "Pallattur",
  "Pallavaram",
  "Pallikaranai",
  "Pallikonda",
  "Pallipalaiyam",
  "Pallipalaiyam Agraharam",
  "Pallipattu",
  "Pammal",
  "Panagudi",
  "Panaimarathupatti",
  "Panapakkam",
  "Panboli",
  "Pandamangalam",
  "Pannaikadu",
  "Pannaipuram",
  "Pannuratti",
  "Panruti",
  "Papanasam",
  "Pappankurichi",
  "Papparapatti",
  "Pappireddipatti",
  "Paramakkudi",
  "Paramankurichi",
  "Paramathi",
  "Parangippettai",
  "Paravai",
  "Pasur",
  "Pathamadai",
  "Pattinam",
  "Pattiviranpatti",
  "Pattukkottai",
  "Pazhugal",
  "Pennadam",
  "Pennagaram",
  "Pennathur",
  "Peraiyur",
  "Peralam",
  "Perambalur",
  "Peranamallur",
  "Peravurani",
  "Periyakodiveri",
  "Periyakulam",
  "Periyanayakkanpalaiyam",
  "Periyanegamam",
  "Periyapatti",
  "Periyasemur",
  "Pernambut",
  "Perumagalur",
  "Perumandi",
  "Perumuchi",
  "Perundurai",
  "Perungalathur",
  "Perungudi",
  "Perungulam",
  "Perur",
  "Perur Chettipalaiyam",
  "Pethampalayam",
  "Pethanaickenpalayam",
  "Pillanallur",
  "Pirkankaranai",
  "Polichalur",
  "Pollachi",
  "Polur",
  "Ponmani",
  "Ponnamaravathi",
  "Ponnampatti",
  "Ponneri",
  "Porur",
  "Pothanur",
  "Pothatturpettai",
  "Pudukadai",
  "Pudukkottai Cantonment",
  "Pudukottai",
  "Pudupalaiyam Aghraharam",
  "Pudupalayam",
  "Pudupatti",
  "Pudupattinam",
  "Pudur",
  "Puduvayal",
  "Pulambadi",
  "Pulampatti",
  "Puliyampatti",
  "Puliyankudi",
  "Puliyur",
  "Pullampadi",
  "Puluvapatti",
  "Punamalli",
  "Punjai Puliyampatti",
  "Punjai Thottakurichi",
  "Punjaipugalur",
  "Puthalam",
  "Putteri",
  "Puvalur",
  "Puzhal",
  "Puzhithivakkam",
  "Rajapalayam",
  "Ramanathapuram",
  "Ramapuram",
  "Rameswaram",
  "Ranipet",
  "Rasipuram",
  "Rayagiri",
  "Rithapuram",
  "Rosalpatti",
  "Rudravathi",
  "Sadayankuppam",
  "Saint Thomas Mount",
  "Salangapalayam",
  "Salem",
  "Samalapuram",
  "Samathur",
  "Sambavar Vadagarai",
  "Sankaramanallur",
  "Sankarankoil",
  "Sankarapuram",
  "Sankari",
  "Sankarnagar",
  "Saravanampatti",
  "Sarcarsamakulam",
  "Sathiyavijayanagaram",
  "Sathuvachari",
  "Sathyamangalam",
  "Sattankulam",
  "Sattur",
  "Sayalgudi",
  "Sayapuram",
  "Seithur",
  "Sembakkam",
  "Semmipalayam",
  "Sennirkuppam",
  "Senthamangalam",
  "Sentharapatti",
  "Senur",
  "Sethiathoppu",
  "Sevilimedu",
  "Sevugampatti",
  "Shenbakkam",
  "Shencottai",
  "Shenkottai",
  "Sholavandan",
  "Sholinganallur",
  "Sholingur",
  "Sholur",
  "Sikkarayapuram",
  "Singampuneri",
  "Singanallur",
  "Singaperumalkoil",
  "Sirapalli",
  "Sirkali",
  "Sirugamani",
  "Sirumugai",
  "Sithayankottai",
  "Sithurajapuram",
  "Sivaganga",
  "Sivagiri",
  "Sivakasi",
  "Sivanthipuram",
  "Sivur",
  "Soranjeri",
  "South Kannanur",
  "South Kodikulam",
  "Srimushnam",
  "Sriperumpudur",
  "Sriramapuram",
  "Srirangam",
  "Srivaikuntam",
  "Srivilliputtur",
  "Suchindram",
  "Suliswaranpatti",
  "Sulur",
  "Sundarapandiam",
  "Sundarapandiapuram",
  "Surampatti",
  "Surandai",
  "Suriyampalayam",
  "Swamimalai",
  "Tambaram",
  "Taramangalam",
  "Tattayyangarpettai",
  "Tayilupatti",
  "Tenkasi",
  "Thadikombu",
  "Thakkolam",
  "Thalainayar",
  "Thalakudi",
  "Thamaraikulam",
  "Thammampatti",
  "Thanjavur",
  "Thanthoni",
  "Tharangambadi",
  "Thedavur",
  "Thenambakkam",
  "Thengampudur",
  "Theni",
  "Theni Allinagaram",
  "Thenkarai",
  "Thenthamaraikulam",
  "Thenthiruperai",
  "Thesur",
  "Thevaram",
  "Thevur",
  "Thiagadurgam",
  "Thiagarajar Colony",
  "Thingalnagar",
  "Thiruchirapalli",
  "Thirukarungudi",
  "Thirukazhukundram",
  "Thirumalayampalayam",
  "Thirumazhisai",
  "Thirunagar",
  "Thirunageswaram",
  "Thirunindravur",
  "Thirunirmalai",
  "Thiruparankundram",
  "Thiruparappu",
  "Thiruporur",
  "Thiruppanandal",
  "Thirupuvanam",
  "Thiruthangal",
  "Thiruthuraipundi",
  "Thiruvaivaru",
  "Thiruvalam",
  "Thiruvarur",
  "Thiruvattaru",
  "Thiruvenkatam",
  "Thiruvennainallur",
  "Thiruvithankodu",
  "Thisayanvilai",
  "Thittacheri",
  "Thondamuthur",
  "Thorapadi",
  "Thottipalayam",
  "Thottiyam",
  "Thudiyalur",
  "Thuthipattu",
  "Thuvakudi",
  "Timiri",
  "Tindivanam",
  "Tinnanur",
  "Tiruchchendur",
  "Tiruchengode",
  "Tirukkalukkundram",
  "Tirukkattuppalli",
  "Tirukkoyilur",
  "Tirumangalam",
  "Tirumullaivasal",
  "Tirumuruganpundi",
  "Tirunageswaram",
  "Tirunelveli",
  "Tirupathur",
  "Tirupattur",
  "Tiruppuvanam",
  "Tirupur",
  "Tirusulam",
  "Tiruttani",
  "Tiruvallur",
  "Tiruvannamalai",
  "Tiruverambur",
  "Tiruverkadu",
  "Tiruvethipuram",
  "Tiruvidaimarudur",
  "Tiruvottiyur",
  "Tittakudi",
  "TNPL Pugalur",
  "Tondi",
  "Turaiyur",
  "Tuticorin",
  "Udagamandalam",
  "Udagamandalam Valley",
  "Udankudi",
  "Udayarpalayam",
  "Udumalaipettai",
  "Udumalpet",
  "Ullur",
  "Ulundurpettai",
  "Unjalaur",
  "Unnamalaikadai",
  "Uppidamangalam",
  "Uppiliapuram",
  "Urachikkottai",
  "Urapakkam",
  "Usilampatti",
  "Uthangarai",
  "Uthayendram",
  "Uthiramerur",
  "Uthukkottai",
  "Uttamapalaiyam",
  "Uttukkuli",
  "Vadakarai Kizhpadugai",
  "Vadakkanandal",
  "Vadakku Valliyur",
  "Vadalur",
  "Vadamadurai",
  "Vadavalli",
  "Vadipatti",
  "Vadugapatti",
  "Vaithiswarankoil",
  "Valangaiman",
  "Valasaravakkam",
  "Valavanur",
  "Vallam",
  "Valparai",
  "Valvaithankoshtam",
  "Vanavasi",
  "Vandalur",
  "Vandavasi",
  "Vandiyur",
  "Vaniputhur",
  "Vaniyambadi",
  "Varadarajanpettai",
  "Varadharajapuram",
  "Vasudevanallur",
  "Vathirairuppu",
  "Vattalkundu",
  "Vazhapadi",
  "Vedapatti",
  "Vedaranniyam",
  "Vedasandur",
  "Velampalaiyam",
  "Velankanni",
  "Vellakinar",
  "Vellakoil",
  "Vellalapatti",
  "Vellalur",
  "Vellanur",
  "Vellimalai",
  "Vellore",
  "Vellottamparappu",
  "Velluru",
  "Vengampudur",
  "Vengathur",
  "Vengavasal",
  "Venghatur",
  "Venkarai",
  "Vennanthur",
  "Veppathur",
  "Verkilambi",
  "Vettaikaranpudur",
  "Vettavalam",
  "Vijayapuri",
  "Vikramasingapuram",
  "Vikravandi",
  "Vilangudi",
  "Vilankurichi",
  "Vilapakkam",
  "Vilathikulam",
  "Vilavur",
  "Villukuri",
  "Villupuram",
  "Viraganur",
  "Virakeralam",
  "Virakkalpudur",
  "Virapandi",
  "Virapandi Cantonment",
  "Virappanchatram",
  "Viravanallur",
  "Virudambattu",
  "Virudhachalam",
  "Virudhunagar",
  "Virupakshipuram",
  "Viswanatham",
  "Vriddhachalam",
  "Walajabad",
  "Walajapet",
  "Wellington",
  "Yercaud",
  "Zamin Uthukuli"
]

const latLongForCountryStateCity = {
  "data": [
    {
      "latitude": 11.052213,
      "longitude": 78.408526,
      "type": "region",
      "name": "Tamil Nadu",
      "number": null,
      "postal_code": null,
      "street": null,
      "confidence": 0.3,
      "region": "Tamil Nadu",
      "region_code": "TN",
      "county": null,
      "locality": null,
      "administrative_area": null,
      "neighbourhood": null,
      "country": "India",
      "country_code": "IND",
      "continent": "Asia",
      "label": "Tamil Nadu, India"
    }
  ]
}

const weatherInfoForLatLong = {
  "lat": 11.0522,
  "lon": 78.4085,
  "timezone": "Asia/Kolkata",
  "timezone_offset": 19800,
  "current": {
    "dt": 1611033817,
    "sunrise": 1611018591,
    "sunset": 1611060232,
    "temp": 24,
    "feels_like": 25.5,
    "pressure": 1014,
    "humidity": 78,
    "dew_point": 19.93,
    "uvi": 7.4,
    "clouds": 40,
    "visibility": 3000,
    "wind_speed": 3.09,
    "wind_deg": 350,
    "weather": [
      {
        "id": 701,
        "main": "Mist",
        "description": "mist",
        "icon": "50d"
      }
    ]
  },
  "daily": [
    {
      "dt": 1611037800,
      "sunrise": 1611018591,
      "sunset": 1611060232,
      "temp": {
        "day": 25.64,
        "min": 19.84,
        "max": 29.42,
        "night": 21.8,
        "eve": 27.29,
        "morn": 20
      },
      "feels_like": {
        "day": 27.56,
        "night": 23.05,
        "eve": 28.28,
        "morn": 21.86
      },
      "pressure": 1014,
      "humidity": 67,
      "dew_point": 19.06,
      "wind_speed": 1.91,
      "wind_deg": 40,
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ],
      "clouds": 23,
      "pop": 0,
      "uvi": 10.39
    },
    {
      "dt": 1611124200,
      "sunrise": 1611104998,
      "sunset": 1611146662,
      "temp": {
        "day": 28.69,
        "min": 20.95,
        "max": 30.52,
        "night": 23.63,
        "eve": 28.82,
        "morn": 21.73
      },
      "feels_like": {
        "day": 29.96,
        "night": 26.28,
        "eve": 30.73,
        "morn": 23.57
      },
      "pressure": 1014,
      "humidity": 46,
      "dew_point": 16.04,
      "wind_speed": 0.97,
      "wind_deg": 84,
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "clouds": 68,
      "pop": 0.14,
      "uvi": 10.99
    },
    {
      "dt": 1611210600,
      "sunrise": 1611191404,
      "sunset": 1611233091,
      "temp": {
        "day": 29.82,
        "min": 22.28,
        "max": 31.14,
        "night": 24.08,
        "eve": 29.91,
        "morn": 22.38
      },
      "feels_like": {
        "day": 33.3,
        "night": 27.43,
        "eve": 32.85,
        "morn": 25.61
      },
      "pressure": 1013,
      "humidity": 59,
      "dew_point": 21.09,
      "wind_speed": 0.96,
      "wind_deg": 62,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": 5,
      "pop": 0.17,
      "uvi": 10.39
    },
    {
      "dt": 1611297000,
      "sunrise": 1611277810,
      "sunset": 1611319519,
      "temp": {
        "day": 29.59,
        "min": 22.45,
        "max": 32.06,
        "night": 23.16,
        "eve": 29.6,
        "morn": 22.45
      },
      "feels_like": {
        "day": 31.79,
        "night": 24.67,
        "eve": 30.89,
        "morn": 25.64
      },
      "pressure": 1013,
      "humidity": 55,
      "dew_point": 19.65,
      "wind_speed": 1.85,
      "wind_deg": 111,
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ],
      "clouds": 11,
      "pop": 0.02,
      "uvi": 11.35
    },
    {
      "dt": 1611383400,
      "sunrise": 1611364214,
      "sunset": 1611405948,
      "temp": {
        "day": 28.52,
        "min": 21.37,
        "max": 31.08,
        "night": 22.12,
        "eve": 29.11,
        "morn": 21.37
      },
      "feels_like": {
        "day": 29.88,
        "night": 23.88,
        "eve": 29.74,
        "morn": 23.79
      },
      "pressure": 1013,
      "humidity": 53,
      "dew_point": 18.11,
      "wind_speed": 2.05,
      "wind_deg": 87,
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02d"
        }
      ],
      "clouds": 22,
      "pop": 0,
      "uvi": 11.21
    },
    {
      "dt": 1611469800,
      "sunrise": 1611450617,
      "sunset": 1611492375,
      "temp": {
        "day": 28.06,
        "min": 20.58,
        "max": 30.78,
        "night": 21.56,
        "eve": 28.42,
        "morn": 20.58
      },
      "feels_like": {
        "day": 29.11,
        "night": 22.59,
        "eve": 28.48,
        "morn": 22.53
      },
      "pressure": 1013,
      "humidity": 53,
      "dew_point": 17.6,
      "wind_speed": 2.23,
      "wind_deg": 102,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": 1,
      "pop": 0,
      "uvi": 12
    },
    {
      "dt": 1611556200,
      "sunrise": 1611537020,
      "sunset": 1611578803,
      "temp": {
        "day": 28.07,
        "min": 19.79,
        "max": 30.96,
        "night": 20.92,
        "eve": 28.43,
        "morn": 19.79
      },
      "feels_like": {
        "day": 29.4,
        "night": 21.54,
        "eve": 27.91,
        "morn": 21.56
      },
      "pressure": 1014,
      "humidity": 50,
      "dew_point": 16.85,
      "wind_speed": 1.3,
      "wind_deg": 80,
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": 0,
      "pop": 0,
      "uvi": 12
    },
    {
      "dt": 1611642600,
      "sunrise": 1611623421,
      "sunset": 1611665229,
      "temp": {
        "day": 27.82,
        "min": 19,
        "max": 30.63,
        "night": 20.46,
        "eve": 28.43,
        "morn": 19
      },
      "feels_like": {
        "day": 28.37,
        "night": 20.83,
        "eve": 28.03,
        "morn": 20.39
      },
      "pressure": 1013,
      "humidity": 44,
      "dew_point": 14.76,
      "wind_speed": 1.24,
      "wind_deg": 81,
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": 42,
      "pop": 0,
      "uvi": 12
    }
  ]
}

export const WEATHER_APP_MOCK_RESPONSE = {
  COUNTRIES_LIST : countriesList,
  STATES_FOR_A_COUNTRY: statesForACountryList,
  CITIES_FOR_A_STATE: citiesInAState,
  LAT_LONG_FOR_COUNTRY_STATE_CITY: latLongForCountryStateCity,
  WEATHER_INFO_FOR_LAT_LONG: weatherInfoForLatLong
}